services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
    ports:
      - "3333:3333"
    environment:
     - PORT=3333
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
  default:
    external:
      name: photo-in-backend_devcontainer_default
