name: Test

on:
  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run eslint
        run: |
          cd /app
          npm install
          npm run lint

      - name: Run jest
        run: |
          cd /app
          npm install
          npm run test
